package com.darly.activities.common;

import java.util.ArrayList;

import android.graphics.Point;

import com.darly.activities.model.IARoomPoint;

/**
 * @author Administrator 现在已知情况下。房间号码和房间点阵。这是一个配置类。
 */
public class IAPoisDataConfig {

	/**
	 * @auther Darly Fronch 2015 下午3:19:29 TODO
	 * @params ks XML中的房间号码关系表，这些数据需要从服务器获取。包括下面的八百伴点阵表格。
	 */
	public static ArrayList<IARoomPoint> getModelTest(int[] ks) {
		// TODO Auto-generated method stub
		ArrayList<IARoomPoint> arrayList = new ArrayList<IARoomPoint>();
		for (int i = 0; i < ks.length; i++) {
			ArrayList<Point> list = new ArrayList<Point>();
			for (int j = 0, sr = babaiban[i].length; j < sr; j += 2) {
				list.add(new Point(babaiban[i][j], babaiban[i][j + 1]));
			}
			arrayList.add(new IARoomPoint(ks[i] + "", list));
		}
		return arrayList;
	}
	// 获取平面图资料八百伴对应的平面图资料
	public static int babaibanw = 2000;
	public static int babaibanh = 1124;
	public static int[][] babaiban = {
			{/* 眼科 */Literal.width * 208 / babaibanw,
					Literal.width * 38 / babaibanw,
					Literal.width * 342 / babaibanw,
					Literal.width * 38 / babaibanw,
					Literal.width * 342 / babaibanw,
					Literal.width * 142 / babaibanw,
					Literal.width * 208 / babaibanw,
					Literal.width * 142 / babaibanw },
			{/* 眼科 */Literal.width * 346 / babaibanw,
					Literal.width * 38 / babaibanw,
					Literal.width * 484 / babaibanw,
					Literal.width * 38 / babaibanw,
					Literal.width * 484 / babaibanw,
					Literal.width * 142 / babaibanw,
					Literal.width * 346 / babaibanw,
					Literal.width * 142 / babaibanw },
			{/* 视力 */Literal.width * 488 / babaibanw,
					Literal.width * 38 / babaibanw,
					Literal.width * 622 / babaibanw,
					Literal.width * 38 / babaibanw,
					Literal.width * 622 / babaibanw,
					Literal.width * 142 / babaibanw,
					Literal.width * 488 / babaibanw,
					Literal.width * 142 / babaibanw },
			{ /* 备用 */Literal.width * 55 / babaibanw,
					Literal.width * 222 / babaibanw,
					Literal.width * 206 / babaibanw,
					Literal.width * 222 / babaibanw,
					Literal.width * 206 / babaibanw,
					Literal.width * 324 / babaibanw,
					Literal.width * 55 / babaibanw,
					Literal.width * 324 / babaibanw },
			{/* 外科 */Literal.width * 55 / babaibanw,
					Literal.width * 438 / babaibanw,
					Literal.width * 206 / babaibanw,
					Literal.width * 438 / babaibanw,
					Literal.width * 206 / babaibanw,
					Literal.width * 526 / babaibanw,
					Literal.width * 55 / babaibanw,
					Literal.width * 526 / babaibanw },
			{/* 外科 */Literal.width * 55 / babaibanw,
					Literal.width * 530 / babaibanw,
					Literal.width * 206 / babaibanw,
					Literal.width * 530 / babaibanw,
					Literal.width * 206 / babaibanw,
					Literal.width * 616 / babaibanw,
					Literal.width * 55 / babaibanw,
					Literal.width * 616 / babaibanw },
			{ /* 备用 */Literal.width * 55 / babaibanw,
					Literal.width * 620 / babaibanw,
					Literal.width * 206 / babaibanw,
					Literal.width * 620 / babaibanw,
					Literal.width * 206 / babaibanw,
					Literal.width * 748 / babaibanw,
					Literal.width * 55 / babaibanw,
					Literal.width * 748 / babaibanw },
			{/* 采血处 */Literal.width * 55 / babaibanw,
					Literal.width * 752 / babaibanw,
					Literal.width * 206 / babaibanw,
					Literal.width * 752 / babaibanw,
					Literal.width * 206 / babaibanw,
					Literal.width * 940 / babaibanw,
					Literal.width * 55 / babaibanw,
					Literal.width * 940 / babaibanw },
			{/* B超彩超室 */Literal.width * 260 / babaibanw,
					Literal.width * 224 / babaibanw,
					Literal.width * 368 / babaibanw,
					Literal.width * 224 / babaibanw,
					Literal.width * 368 / babaibanw,
					Literal.width * 327 / babaibanw,
					Literal.width * 260 / babaibanw,
					Literal.width * 327 / babaibanw },
			{/* B超彩超室 */Literal.width * 372 / babaibanw,
					Literal.width * 224 / babaibanw,
					Literal.width * 484 / babaibanw,
					Literal.width * 224 / babaibanw,
					Literal.width * 484 / babaibanw,
					Literal.width * 327 / babaibanw,
					Literal.width * 372 / babaibanw,
					Literal.width * 327 / babaibanw },
			{/* B超 彩超室 */Literal.width * 488 / babaibanw,
					Literal.width * 224 / babaibanw,
					Literal.width * 620 / babaibanw,
					Literal.width * 224 / babaibanw,
					Literal.width * 620 / babaibanw,
					Literal.width * 327 / babaibanw,
					Literal.width * 488 / babaibanw,
					Literal.width * 327 / babaibanw },
			{/* 内科 */Literal.width * 260 / babaibanw,
					Literal.width * 330 / babaibanw,
					Literal.width * 368 / babaibanw,
					Literal.width * 330 / babaibanw,
					Literal.width * 368 / babaibanw,
					Literal.width * 436 / babaibanw,
					Literal.width * 260 / babaibanw,
					Literal.width * 436 / babaibanw },
			{/* 内科 */Literal.width * 372 / babaibanw,
					Literal.width * 330 / babaibanw,
					Literal.width * 484 / babaibanw,
					Literal.width * 330 / babaibanw,
					Literal.width * 484 / babaibanw,
					Literal.width * 436 / babaibanw,
					Literal.width * 372 / babaibanw,
					Literal.width * 436 / babaibanw },
			{/* 心电图 */Literal.width * 488 / babaibanw,
					Literal.width * 330 / babaibanw,
					Literal.width * 620 / babaibanw,
					Literal.width * 330 / babaibanw,
					Literal.width * 620 / babaibanw,
					Literal.width * 436 / babaibanw,
					Literal.width * 488 / babaibanw,
					Literal.width * 436 / babaibanw },
			{/* 内科 */Literal.width * 426 / babaibanw,
					Literal.width * 438 / babaibanw,
					Literal.width * 540 / babaibanw,
					Literal.width * 438 / babaibanw,
					Literal.width * 540 / babaibanw,
					Literal.width * 540 / babaibanw,
					Literal.width * 426 / babaibanw,
					Literal.width * 540 / babaibanw },
			{/* 内科 */Literal.width * 428 / babaibanw,
					Literal.width * 438 / babaibanw,
					Literal.width * 540 / babaibanw,
					Literal.width * 438 / babaibanw,
					Literal.width * 540 / babaibanw,
					Literal.width * 540 / babaibanw,
					Literal.width * 428 / babaibanw,
					Literal.width * 540 / babaibanw },
			{/* 心电图 */Literal.width * 258 / babaibanw,
					Literal.width * 544 / babaibanw,
					Literal.width * 370 / babaibanw,
					Literal.width * 544 / babaibanw,
					Literal.width * 370 / babaibanw,
					Literal.width * 648 / babaibanw,
					Literal.width * 258 / babaibanw,
					Literal.width * 648 / babaibanw },
			{/* 心电图 */Literal.width * 374 / babaibanw,
					Literal.width * 544 / babaibanw,
					Literal.width * 540 / babaibanw,
					Literal.width * 544 / babaibanw,
					Literal.width * 540 / babaibanw,
					Literal.width * 648 / babaibanw,
					Literal.width * 374 / babaibanw,
					Literal.width * 648 / babaibanw },
			{/* 心电图110 */Literal.width * 374 / babaibanw,
					Literal.width * 544 / babaibanw,
					Literal.width * 540 / babaibanw,
					Literal.width * 544 / babaibanw,
					Literal.width * 540 / babaibanw,
					Literal.width * 648 / babaibanw,
					Literal.width * 374 / babaibanw,
					Literal.width * 648 / babaibanw },
			{/* 耳鼻喉 */Literal.width * 258 / babaibanw,
					Literal.width * 652 / babaibanw,
					Literal.width * 330 / babaibanw,
					Literal.width * 652 / babaibanw,
					Literal.width * 330 / babaibanw,
					Literal.width * 810 / babaibanw,
					Literal.width * 258 / babaibanw,
					Literal.width * 810 / babaibanw },
			{/* 耳鼻喉 */Literal.width * 334 / babaibanw,
					Literal.width * 652 / babaibanw,
					Literal.width * 406 / babaibanw,
					Literal.width * 652 / babaibanw,
					Literal.width * 406 / babaibanw,
					Literal.width * 810 / babaibanw,
					Literal.width * 334 / babaibanw,
					Literal.width * 810 / babaibanw },
			{/* 一般检查 */Literal.width * 410 / babaibanw,
					Literal.width * 652 / babaibanw,
					Literal.width * 498 / babaibanw,
					Literal.width * 652 / babaibanw,
					Literal.width * 498 / babaibanw,
					Literal.width * 810 / babaibanw,
					Literal.width * 410 / babaibanw,
					Literal.width * 810 / babaibanw },
			{/* 外科 */Literal.width * 502 / babaibanw,
					Literal.width * 652 / babaibanw,
					Literal.width * 590 / babaibanw,
					Literal.width * 652 / babaibanw,
					Literal.width * 590 / babaibanw,
					Literal.width * 810 / babaibanw,
					Literal.width * 502 / babaibanw,
					Literal.width * 810 / babaibanw },
			{/* B超彩超室 */Literal.width * 674 / babaibanw,
					Literal.width * 188 / babaibanw,
					Literal.width * 820 / babaibanw,
					Literal.width * 188 / babaibanw,
					Literal.width * 820 / babaibanw,
					Literal.width * 313 / babaibanw,
					Literal.width * 674 / babaibanw,
					Literal.width * 313 / babaibanw },
			{/* 妇科 */Literal.width * 674 / babaibanw,
					Literal.width * 388 / babaibanw,
					Literal.width * 820 / babaibanw,
					Literal.width * 388 / babaibanw,
					Literal.width * 820 / babaibanw,
					Literal.width * 517 / babaibanw,
					Literal.width * 674 / babaibanw,
					Literal.width * 517 / babaibanw },
			{/* 妇科 */Literal.width * 674 / babaibanw,
					Literal.width * 520 / babaibanw,
					Literal.width * 820 / babaibanw,
					Literal.width * 520 / babaibanw,
					Literal.width * 820 / babaibanw,
					Literal.width * 648 / babaibanw,
					Literal.width * 674 / babaibanw,
					Literal.width * 648 / babaibanw },
			{/* 内科 */Literal.width * 674 / babaibanw,
					Literal.width * 654 / babaibanw,
					Literal.width * 820 / babaibanw,
					Literal.width * 654 / babaibanw,
					Literal.width * 820 / babaibanw,
					Literal.width * 780 / babaibanw,
					Literal.width * 674 / babaibanw,
					Literal.width * 780 / babaibanw },
			{/* 口腔科 */Literal.width * 1204 / babaibanw,
					Literal.width * 182 / babaibanw,
					Literal.width * 1395 / babaibanw,
					Literal.width * 182 / babaibanw,
					Literal.width * 1298 / babaibanw,
					Literal.width * 277 / babaibanw },
			{/* 中医科 */Literal.width * 1300 / babaibanw,
					Literal.width * 280 / babaibanw,
					Literal.width * 1420 / babaibanw,
					Literal.width * 162 / babaibanw,
					Literal.width * 1478 / babaibanw,
					Literal.width * 220 / babaibanw,
					Literal.width * 1356 / babaibanw,
					Literal.width * 338 / babaibanw },
			{/* 钼靶室 */Literal.width * 1361 / babaibanw,
					Literal.width * 340 / babaibanw,
					Literal.width * 1481 / babaibanw,
					Literal.width * 224 / babaibanw,
					Literal.width * 1541 / babaibanw,
					Literal.width * 282 / babaibanw,
					Literal.width * 1420 / babaibanw,
					Literal.width * 400 / babaibanw },
			{/* DR */Literal.width * 1528 / babaibanw,
					Literal.width * 424 / babaibanw,
					Literal.width * 1609 / babaibanw,
					Literal.width * 345 / babaibanw,
					Literal.width * 1645 / babaibanw,
					Literal.width * 345 / babaibanw,
					Literal.width * 1645 / babaibanw,
					Literal.width * 462 / babaibanw,
					Literal.width * 1537 / babaibanw,
					Literal.width * 462 / babaibanw,
					Literal.width * 1537 / babaibanw,
					Literal.width * 424 / babaibanw },
			{/* CT室 */Literal.width * 1648 / babaibanw,
					Literal.width * 345 / babaibanw,
					Literal.width * 1808 / babaibanw,
					Literal.width * 345 / babaibanw,
					Literal.width * 1808 / babaibanw,
					Literal.width * 462 / babaibanw,
					Literal.width * 1648 / babaibanw,
					Literal.width * 462 / babaibanw },
			{/* 动脉硬化 */Literal.width * 1717 / babaibanw,
					Literal.width * 552 / babaibanw,
					Literal.width * 1808 / babaibanw,
					Literal.width * 467 / babaibanw,
					Literal.width * 1808 / babaibanw,
					Literal.width * 474 / babaibanw,
					Literal.width * 1866 / babaibanw,
					Literal.width * 529 / babaibanw,
					Literal.width * 1777 / babaibanw,
					Literal.width * 613 / babaibanw },
			{/* 备用 */Literal.width * 1811 / babaibanw,
					Literal.width * 639 / babaibanw,
					Literal.width * 1893 / babaibanw,
					Literal.width * 556 / babaibanw,
					Literal.width * 1950 / babaibanw,
					Literal.width * 611 / babaibanw,
					Literal.width * 1867 / babaibanw,
					Literal.width * 694 / babaibanw },
			{/* 骨密度 */Literal.width * 1678 / babaibanw,
					Literal.width * 772 / babaibanw,
					Literal.width * 1808 / babaibanw,
					Literal.width * 642 / babaibanw,
					Literal.width * 1864 / babaibanw,
					Literal.width * 698 / babaibanw,
					Literal.width * 1735 / babaibanw,
					Literal.width * 829 / babaibanw },
			{/* 经颅多普勒 */Literal.width * 1542 / babaibanw,
					Literal.width * 907 / babaibanw,
					Literal.width * 1675 / babaibanw,
					Literal.width * 775 / babaibanw,
					Literal.width * 1731 / babaibanw,
					Literal.width * 832 / babaibanw,
					Literal.width * 1600 / babaibanw,
					Literal.width * 965 / babaibanw },
			{/* 肺功能 */Literal.width * 1425 / babaibanw,
					Literal.width * 940 / babaibanw,
					Literal.width * 1570 / babaibanw,
					Literal.width * 940 / babaibanw,
					Literal.width * 1600 / babaibanw,
					Literal.width * 970 / babaibanw,
					Literal.width * 1600 / babaibanw,
					Literal.width * 1042 / babaibanw,
					Literal.width * 1425 / babaibanw,
					Literal.width * 1042 / babaibanw },
			{/* 000 */Literal.width * 823 / babaibanw,
					Literal.width * 196 / babaibanw,
					Literal.width * 942 / babaibanw,
					Literal.width * 311 / babaibanw,
					Literal.width * 878 / babaibanw,
					Literal.width * 376 / babaibanw,
					Literal.width * 823 / babaibanw,
					Literal.width * 321 / babaibanw } };

	// 获取平面图资料静安对应的平面图资料

	public static int jinganw = 2000;
	public static int jinganh = 1124;
	public static int[][] jingan = {
			{/* 检验科 */Literal.width * 518 / jinganw,
					Literal.width * 151 / jinganw,
					Literal.width * 780 / jinganw,
					Literal.width * 9 / jinganw,
					Literal.width * 802 / jinganw,
					Literal.width * 9 / jinganw,
					Literal.width * 802 / jinganw,
					Literal.width * 110 / jinganw,
					Literal.width * 518 / jinganw,
					Literal.width * 269 / jinganw },
			{/* DR房間 */Literal.width * 806 / jinganw,
					Literal.width * 9 / jinganw,
					Literal.width * 1079 / jinganw,
					Literal.width * 9 / jinganw,
					Literal.width * 1079 / jinganw,
					Literal.width * 112 / jinganw,
					Literal.width * 806 / jinganw,
					Literal.width * 112 / jinganw },
			{/* 钼钯 */Literal.width * 1082 / jinganw,
					Literal.width * 9 / jinganw,
					Literal.width * 1247 / jinganw,
					Literal.width * 9 / jinganw,
					Literal.width * 1247 / jinganw,
					Literal.width * 112 / jinganw,
					Literal.width * 1082 / jinganw,
					Literal.width * 112 / jinganw },
			// 进行修改
			{/* 备用227 */Literal.width * 1236 / jinganw,
					Literal.width * 170 / jinganw,
					Literal.width * 1329 / jinganw,
					Literal.width * 87 / jinganw,
					Literal.width * 1351 / jinganw,
					Literal.width * 110 / jinganw,
					Literal.width * 1260 / jinganw,
					Literal.width * 194 / jinganw },
			{/* 肺功能228 */Literal.width * 1259 / jinganw,
					Literal.width * 198 / jinganw,
					Literal.width * 1354 / jinganw,
					Literal.width * 115 / jinganw,
					Literal.width * 1408 / jinganw,
					Literal.width * 166 / jinganw,
					Literal.width * 1317 / jinganw,
					Literal.width * 251 / jinganw },
			{/* 骨密度 */Literal.width * 1065 / jinganw,
					Literal.width * 144 / jinganw,
					Literal.width * 1148 / jinganw,
					Literal.width * 228 / jinganw,
					Literal.width * 1092 / jinganw,
					Literal.width * 285 / jinganw,
					Literal.width * 1008 / jinganw,
					Literal.width * 201 / jinganw },
			{/* 经颅多普勒 */Literal.width * 1003 / jinganw,
					Literal.width * 204 / jinganw,
					Literal.width * 1124 / jinganw,
					Literal.width * 324 / jinganw,
					Literal.width * 1069 / jinganw,
					Literal.width * 378 / jinganw,
					Literal.width * 948 / jinganw,
					Literal.width * 260 / jinganw },
			{/* B超219 */Literal.width * 452 / jinganw,
					Literal.width * 313 / jinganw,
					Literal.width * 583 / jinganw,
					Literal.width * 313 / jinganw,
					Literal.width * 583 / jinganw,
					Literal.width * 392 / jinganw,
					Literal.width * 452 / jinganw,
					Literal.width * 392 / jinganw },
			{/* B超218 */Literal.width * 218 / jinganw,
					Literal.width * 313 / jinganw,
					Literal.width * 446 / jinganw,
					Literal.width * 313 / jinganw,
					Literal.width * 446 / jinganw,
					Literal.width * 392 / jinganw,
					Literal.width * 218 / jinganw,
					Literal.width * 392 / jinganw },
			{/* 心电图217 */Literal.width * 218 / jinganw,
					Literal.width * 395 / jinganw,
					Literal.width * 422 / jinganw,
					Literal.width * 395 / jinganw,
					Literal.width * 422 / jinganw,
					Literal.width * 465 / jinganw,
					Literal.width * 218 / jinganw,
					Literal.width * 465 / jinganw },
			{/* 内科238 */Literal.width * 1128 / jinganw,
					Literal.width * 331 / jinganw,
					Literal.width * 1201 / jinganw,
					Literal.width * 402 / jinganw,
					Literal.width * 1146 / jinganw,
					Literal.width * 456 / jinganw,
					Literal.width * 1072 / jinganw,
					Literal.width * 384 / jinganw },
			{/* 239 */Literal.width * 1186 / jinganw,
					Literal.width * 268 / jinganw,
					Literal.width * 1260 / jinganw,
					Literal.width * 340 / jinganw,
					Literal.width * 1203 / jinganw,
					Literal.width * 398 / jinganw,
					Literal.width * 1130 / jinganw,
					Literal.width * 325 / jinganw },
			{/* 226 */Literal.width * 1318 / jinganw,
					Literal.width * 258 / jinganw,
					Literal.width * 1413 / jinganw,
					Literal.width * 174 / jinganw,
					Literal.width * 1470 / jinganw,
					Literal.width * 226 / jinganw,
					Literal.width * 1374 / jinganw,
					Literal.width * 311 / jinganw },
			{/* 报告室 */Literal.width * 1473 / jinganw,
					Literal.width * 230 / jinganw,
					Literal.width * 1617 / jinganw,
					Literal.width * 374 / jinganw,
					Literal.width * 1314 / jinganw,
					Literal.width * 374 / jinganw },
			{/* B超253 */Literal.width * 1623 / jinganw,
					Literal.width * 377 / jinganw,
					Literal.width * 1725 / jinganw,
					Literal.width * 377 / jinganw,
					Literal.width * 1725 / jinganw,
					Literal.width * 508 / jinganw,
					Literal.width * 1623 / jinganw,
					Literal.width * 508 / jinganw },
			{/* 男外科 252 */Literal.width * 1527 / jinganw,
					Literal.width * 377 / jinganw,
					Literal.width * 1619 / jinganw,
					Literal.width * 377 / jinganw,
					Literal.width * 1619 / jinganw,
					Literal.width * 508 / jinganw,
					Literal.width * 1527 / jinganw,
					Literal.width * 508 / jinganw },
			{/* 男外科 251 */Literal.width * 1425 / jinganw,
					Literal.width * 377 / jinganw,
					Literal.width * 1523 / jinganw,
					Literal.width * 377 / jinganw,
					Literal.width * 1523 / jinganw,
					Literal.width * 508 / jinganw,
					Literal.width * 1425 / jinganw,
					Literal.width * 508 / jinganw },
			{/* 心电图 250 */Literal.width * 1305 / jinganw,
					Literal.width * 377 / jinganw,
					Literal.width * 1415 / jinganw,
					Literal.width * 377 / jinganw,
					Literal.width * 1415 / jinganw,
					Literal.width * 508 / jinganw,
					Literal.width * 1305 / jinganw,
					Literal.width * 508 / jinganw },
			{/* 心电图 216 */Literal.width * 221 / jinganw,
					Literal.width * 469 / jinganw,
					Literal.width * 424 / jinganw,
					Literal.width * 469 / jinganw,
					Literal.width * 424 / jinganw,
					Literal.width * 539 / jinganw,
					Literal.width * 221 / jinganw,
					Literal.width * 539 / jinganw },
			{/* 妇科212 */Literal.width * 220 / jinganw,
					Literal.width * 544 / jinganw,
					Literal.width * 348 / jinganw,
					Literal.width * 544 / jinganw,
					Literal.width * 348 / jinganw,
					Literal.width * 711 / jinganw,
					Literal.width * 220 / jinganw,
					Literal.width * 711 / jinganw },
			{/* 妇科213 */Literal.width * 352 / jinganw,
					Literal.width * 543 / jinganw,
					Literal.width * 470 / jinganw,
					Literal.width * 543 / jinganw,
					Literal.width * 470 / jinganw,
					Literal.width * 623 / jinganw,
					Literal.width * 352 / jinganw,
					Literal.width * 623 / jinganw },
			{/* 外科215 */Literal.width * 475 / jinganw,
					Literal.width * 543 / jinganw,
					Literal.width * 585 / jinganw,
					Literal.width * 543 / jinganw,
					Literal.width * 585 / jinganw,
					Literal.width * 623 / jinganw,
					Literal.width * 475 / jinganw,
					Literal.width * 623 / jinganw },
			{/* B超255 */Literal.width * 1649 / jinganw,
					Literal.width * 513 / jinganw,
					Literal.width * 1726 / jinganw,
					Literal.width * 513 / jinganw,
					Literal.width * 1726 / jinganw,
					Literal.width * 593 / jinganw,
					Literal.width * 1649 / jinganw,
					Literal.width * 593 / jinganw },
			{/* 备用237 */Literal.width * 1293 / jinganw,
					Literal.width * 625 / jinganw,
					Literal.width * 1368 / jinganw,
					Literal.width * 559 / jinganw,
					Literal.width * 1408 / jinganw,
					Literal.width * 596 / jinganw,
					Literal.width * 1334 / jinganw,
					Literal.width * 666 / jinganw },
			{/* 备用236 */Literal.width * 1147 / jinganw,
					Literal.width * 769 / jinganw,
					Literal.width * 1220 / jinganw,
					Literal.width * 696 / jinganw,
					Literal.width * 1261 / jinganw,
					Literal.width * 737 / jinganw,
					Literal.width * 1184 / jinganw,
					Literal.width * 814 / jinganw },
			{/* 眼科208 */Literal.width * 665 / jinganw,
					Literal.width * 615 / jinganw,
					Literal.width * 802 / jinganw,
					Literal.width * 615 / jinganw,
					Literal.width * 802 / jinganw,
					Literal.width * 699 / jinganw,
					Literal.width * 665 / jinganw,
					Literal.width * 699 / jinganw },
			{/* B超211 */Literal.width * 220 / jinganw,
					Literal.width * 716 / jinganw,
					Literal.width * 373 / jinganw,
					Literal.width * 716 / jinganw,
					Literal.width * 373 / jinganw,
					Literal.width * 796 / jinganw,
					Literal.width * 220 / jinganw,
					Literal.width * 796 / jinganw },
			{/* B超210 */Literal.width * 379 / jinganw,
					Literal.width * 716 / jinganw,
					Literal.width * 479 / jinganw,
					Literal.width * 716 / jinganw,
					Literal.width * 479 / jinganw,
					Literal.width * 796 / jinganw,
					Literal.width * 379 / jinganw,
					Literal.width * 796 / jinganw },
			{/* 内科209 */Literal.width * 482 / jinganw,
					Literal.width * 716 / jinganw,
					Literal.width * 584 / jinganw,
					Literal.width * 716 / jinganw,
					Literal.width * 584 / jinganw,
					Literal.width * 796 / jinganw,
					Literal.width * 482 / jinganw,
					Literal.width * 796 / jinganw },
			{/* 视力207 */Literal.width * 665 / jinganw,
					Literal.width * 704 / jinganw,
					Literal.width * 802 / jinganw,
					Literal.width * 704 / jinganw,
					Literal.width * 802 / jinganw,
					Literal.width * 791 / jinganw,
					Literal.width * 665 / jinganw,
					Literal.width * 791 / jinganw },
			{/* 233 */Literal.width * 806 / jinganw,
					Literal.width * 612 / jinganw,
					Literal.width * 839 / jinganw,
					Literal.width * 612 / jinganw,
					Literal.width * 946 / jinganw,
					Literal.width * 719 / jinganw,
					Literal.width * 946 / jinganw,
					Literal.width * 804 / jinganw,
					Literal.width * 806 / jinganw,
					Literal.width * 804 / jinganw },
			{/* 备用235 */Literal.width * 898 / jinganw,
					Literal.width * 549 / jinganw,
					Literal.width * 1011 / jinganw,
					Literal.width * 663 / jinganw,
					Literal.width * 954 / jinganw,
					Literal.width * 720 / jinganw,
					Literal.width * 840 / jinganw,
					Literal.width * 608 / jinganw },
			{/* 231 */Literal.width * 1038 / jinganw,
					Literal.width * 818 / jinganw,
					Literal.width * 1177 / jinganw,
					Literal.width * 818 / jinganw,
					Literal.width * 1177 / jinganw,
					Literal.width * 876 / jinganw,
					Literal.width * 1038 / jinganw,
					Literal.width * 876 / jinganw },
			{/* 232 */Literal.width * 806 / jinganw,
					Literal.width * 808 / jinganw,
					Literal.width * 946 / jinganw,
					Literal.width * 808 / jinganw,
					Literal.width * 946 / jinganw,
					Literal.width * 885 / jinganw,
					Literal.width * 806 / jinganw,
					Literal.width * 885 / jinganw },
			{/* 耳鼻喉科206 */Literal.width * 663 / jinganw,
					Literal.width * 796 / jinganw,
					Literal.width * 802 / jinganw,
					Literal.width * 796 / jinganw,
					Literal.width * 802 / jinganw,
					Literal.width * 905 / jinganw,
					Literal.width * 663 / jinganw,
					Literal.width * 905 / jinganw },
			{/* 备用205 */Literal.width * 662 / jinganw,
					Literal.width * 908 / jinganw,
					Literal.width * 802 / jinganw,
					Literal.width * 908 / jinganw,
					Literal.width * 802 / jinganw,
					Literal.width * 961 / jinganw,
					Literal.width * 662 / jinganw,
					Literal.width * 961 / jinganw },
			{/* 备用203 */Literal.width * 662 / jinganw,
					Literal.width * 965 / jinganw,
					Literal.width * 802 / jinganw,
					Literal.width * 965 / jinganw,
					Literal.width * 802 / jinganw,
					Literal.width * 1022 / jinganw,
					Literal.width * 662 / jinganw,
					Literal.width * 1022 / jinganw },
			{/* 一般检查228 */Literal.width * 806 / jinganw,
					Literal.width * 889 / jinganw,
					Literal.width * 946 / jinganw,
					Literal.width * 889 / jinganw,
					Literal.width * 946 / jinganw,
					Literal.width * 1021 / jinganw,
					Literal.width * 806 / jinganw,
					Literal.width * 1021 / jinganw },
			{/* 230 */Literal.width * 1037 / jinganw,
					Literal.width * 880 / jinganw,
					Literal.width * 1177 / jinganw,
					Literal.width * 880 / jinganw,
					Literal.width * 1177 / jinganw,
					Literal.width * 931 / jinganw,
					Literal.width * 1037 / jinganw,
					Literal.width * 931 / jinganw },
			{/* 229 */Literal.width * 1037 / jinganw,
					Literal.width * 936 / jinganw,
					Literal.width * 1177 / jinganw,
					Literal.width * 936 / jinganw,
					Literal.width * 1177 / jinganw,
					Literal.width * 1032 / jinganw,
					Literal.width * 1037 / jinganw,
					Literal.width * 1032 / jinganw },
			{/* 采血处201 */Literal.width * 501 / jinganw,
					Literal.width * 984 / jinganw,
					Literal.width * 501 / jinganw,
					Literal.width * 1111 / jinganw,
					Literal.width * 627 / jinganw,
					Literal.width * 1111 / jinganw } };

	// 获取平面图资料TC2对应的平面图资料()徐汇地区的平面图
	public static int xuhuiw = 2000;
	public static int xuhuih = 1124;
	public static int[][] xuhui = {
			{/* DR房間136 */Literal.width * 231 / jinganw,
					Literal.width * 24 / jinganw,
					Literal.width * 428 / jinganw,
					Literal.width * 24 / jinganw,
					Literal.width * 428 / jinganw,
					Literal.width * 172 / jinganw,
					Literal.width * 231 / jinganw,
					Literal.width * 172 / jinganw },
			{/* CT房間 137 */Literal.width * 431 / jinganw,
					Literal.width * 24 / jinganw,
					Literal.width * 766 / jinganw,
					Literal.width * 24 / jinganw,
					Literal.width * 766 / jinganw,
					Literal.width * 172 / jinganw,
					Literal.width * 431 / jinganw,
					Literal.width * 172 / jinganw },
			{/* 采血处104 */Literal.width * 1590 / jinganw,
					Literal.width * 595 / jinganw,
					Literal.width * 1732 / jinganw,
					Literal.width * 595 / jinganw,
					Literal.width * 1732 / jinganw,
					Literal.width * 767 / jinganw,
					Literal.width * 1590 / jinganw,
					Literal.width * 767 / jinganw },
			{/* 检验科105 */Literal.width * 1590 / jinganw,
					Literal.width * 770 / jinganw,
					Literal.width * 1732 / jinganw,
					Literal.width * 770 / jinganw,
					Literal.width * 1732 / jinganw,
					Literal.width * 945 / jinganw,
					Literal.width * 1590 / jinganw,
					Literal.width * 945 / jinganw },
			{/* 一般项目106 */Literal.width * 1536 / jinganw,
					Literal.width * 991 / jinganw,
					Literal.width * 1732 / jinganw,
					Literal.width * 991 / jinganw,
					Literal.width * 1732 / jinganw,
					Literal.width * 1102 / jinganw,
					Literal.width * 1536 / jinganw,
					Literal.width * 1102 / jinganw },
			{/* 口腔科107 */Literal.width * 1416 / jinganw,
					Literal.width * 991 / jinganw,
					Literal.width * 1533 / jinganw,
					Literal.width * 991 / jinganw,
					Literal.width * 1533 / jinganw,
					Literal.width * 1102 / jinganw,
					Literal.width * 1416 / jinganw,
					Literal.width * 1102 / jinganw },
			{/* 心电图108 */Literal.width * 1294 / jinganw,
					Literal.width * 991 / jinganw,
					Literal.width * 1412 / jinganw,
					Literal.width * 991 / jinganw,
					Literal.width * 1412 / jinganw,
					Literal.width * 1102 / jinganw,
					Literal.width * 1294 / jinganw,
					Literal.width * 1102 / jinganw },
			{/* 心电图109 */Literal.width * 1164 / jinganw,
					Literal.width * 991 / jinganw,
					Literal.width * 1291 / jinganw,
					Literal.width * 991 / jinganw,
					Literal.width * 1291 / jinganw,
					Literal.width * 1102 / jinganw,
					Literal.width * 1164 / jinganw,
					Literal.width * 1102 / jinganw },
			{/* B超110 */Literal.width * 1062 / jinganw,
					Literal.width * 991 / jinganw,
					Literal.width * 1160 / jinganw,
					Literal.width * 991 / jinganw,
					Literal.width * 1160 / jinganw,
					Literal.width * 1102 / jinganw,
					Literal.width * 1062 / jinganw,
					Literal.width * 1102 / jinganw },
			{/* B超111 */Literal.width * 962 / jinganw,
					Literal.width * 991 / jinganw,
					Literal.width * 1059 / jinganw,
					Literal.width * 991 / jinganw,
					Literal.width * 1059 / jinganw,
					Literal.width * 1102 / jinganw,
					Literal.width * 962 / jinganw,
					Literal.width * 1102 / jinganw },
			{/* B超112 */Literal.width * 833 / jinganw,
					Literal.width * 991 / jinganw,
					Literal.width * 958 / jinganw,
					Literal.width * 991 / jinganw,
					Literal.width * 958 / jinganw,
					Literal.width * 1102 / jinganw,
					Literal.width * 833 / jinganw,
					Literal.width * 1102 / jinganw },
			{/* 钼靶124 */Literal.width * 563 / jinganw,
					Literal.width * 991 / jinganw,
					Literal.width * 829 / jinganw,
					Literal.width * 991 / jinganw,
					Literal.width * 829 / jinganw,
					Literal.width * 1102 / jinganw,
					Literal.width * 563 / jinganw,
					Literal.width * 1102 / jinganw },
			{/* 多普勒129 */Literal.width * 338 / jinganw,
					Literal.width * 572 / jinganw,
					Literal.width * 562 / jinganw,
					Literal.width * 572 / jinganw,
					Literal.width * 562 / jinganw,
					Literal.width * 711 / jinganw,
					Literal.width * 338 / jinganw,
					Literal.width * 711 / jinganw },
			{/* 呼气试验肺功能130 */Literal.width * 228 / jinganw,
					Literal.width * 572 / jinganw,
					Literal.width * 335 / jinganw,
					Literal.width * 572 / jinganw,
					Literal.width * 335 / jinganw,
					Literal.width * 711 / jinganw,
					Literal.width * 228 / jinganw,
					Literal.width * 711 / jinganw },
			{/* 中医科131 */Literal.width * 228 / jinganw,
					Literal.width * 440 / jinganw,
					Literal.width * 340 / jinganw,
					Literal.width * 440 / jinganw,
					Literal.width * 340 / jinganw,
					Literal.width * 536 / jinganw,
					Literal.width * 228 / jinganw,
					Literal.width * 536 / jinganw },
			{/* 备用室132 */Literal.width * 228 / jinganw,
					Literal.width * 256 / jinganw,
					Literal.width * 340 / jinganw,
					Literal.width * 256 / jinganw,
					Literal.width * 340 / jinganw,
					Literal.width * 408 / jinganw,
					Literal.width * 228 / jinganw,
					Literal.width * 408 / jinganw },
			{/* 动脉粥样硬化133 */Literal.width * 342 / jinganw,
					Literal.width * 256 / jinganw,
					Literal.width * 452 / jinganw,
					Literal.width * 256 / jinganw,
					Literal.width * 452 / jinganw,
					Literal.width * 408 / jinganw,
					Literal.width * 342 / jinganw,
					Literal.width * 408 / jinganw },
			{/* 人体成分骨密度134 */Literal.width * 455 / jinganw,
					Literal.width * 256 / jinganw,
					Literal.width * 566 / jinganw,
					Literal.width * 256 / jinganw,
					Literal.width * 566 / jinganw,
					Literal.width * 408 / jinganw,
					Literal.width * 455 / jinganw,
					Literal.width * 408 / jinganw },
			{/* 视力116 */Literal.width * 1279 / jinganw,
					Literal.width * 598 / jinganw,
					Literal.width * 1435 / jinganw,
					Literal.width * 598 / jinganw,
					Literal.width * 1435 / jinganw,
					Literal.width * 678 / jinganw,
					Literal.width * 1279 / jinganw,
					Literal.width * 678 / jinganw },
			{/* 眼科115 */Literal.width * 1279 / jinganw,
					Literal.width * 682 / jinganw,
					Literal.width * 1435 / jinganw,
					Literal.width * 682 / jinganw,
					Literal.width * 1435 / jinganw,
					Literal.width * 761 / jinganw,
					Literal.width * 1279 / jinganw,
					Literal.width * 761 / jinganw },
			{/* 眼科114 */Literal.width * 1279 / jinganw,
					Literal.width * 765 / jinganw,
					Literal.width * 1435 / jinganw,
					Literal.width * 765 / jinganw,
					Literal.width * 1435 / jinganw,
					Literal.width * 840 / jinganw,
					Literal.width * 1279 / jinganw,
					Literal.width * 840 / jinganw },
			{/* 耳鼻喉113 */Literal.width * 1279 / jinganw,
					Literal.width * 844 / jinganw,
					Literal.width * 1435 / jinganw,
					Literal.width * 844 / jinganw,
					Literal.width * 1435 / jinganw,
					Literal.width * 924 / jinganw,
					Literal.width * 1279 / jinganw,
					Literal.width * 924 / jinganw },
			{/* 男外科120 */Literal.width * 1118 / jinganw,
					Literal.width * 598 / jinganw,
					Literal.width * 1274 / jinganw,
					Literal.width * 598 / jinganw,
					Literal.width * 1274 / jinganw,
					Literal.width * 678 / jinganw,
					Literal.width * 1118 / jinganw,
					Literal.width * 678 / jinganw },
			{/* 中医科119 */Literal.width * 1118 / jinganw,
					Literal.width * 682 / jinganw,
					Literal.width * 1274 / jinganw,
					Literal.width * 682 / jinganw,
					Literal.width * 1274 / jinganw,
					Literal.width * 761 / jinganw,
					Literal.width * 1118 / jinganw,
					Literal.width * 761 / jinganw },
			{/* 男内科118 */Literal.width * 1118 / jinganw,
					Literal.width * 765 / jinganw,
					Literal.width * 1274 / jinganw,
					Literal.width * 765 / jinganw,
					Literal.width * 1274 / jinganw,
					Literal.width * 840 / jinganw,
					Literal.width * 1118 / jinganw,
					Literal.width * 840 / jinganw },
			{/* 男外科117 */Literal.width * 1118 / jinganw,
					Literal.width * 844 / jinganw,
					Literal.width * 1274 / jinganw,
					Literal.width * 844 / jinganw,
					Literal.width * 1274 / jinganw,
					Literal.width * 924 / jinganw,
					Literal.width * 1118 / jinganw,
					Literal.width * 924 / jinganw },
			{/* 女心电图123 */Literal.width * 891 / jinganw,
					Literal.width * 598 / jinganw,
					Literal.width * 1024 / jinganw,
					Literal.width * 598 / jinganw,
					Literal.width * 1024 / jinganw,
					Literal.width * 697 / jinganw,
					Literal.width * 891 / jinganw,
					Literal.width * 697 / jinganw },
			{/* B超122 */Literal.width * 891 / jinganw,
					Literal.width * 702 / jinganw,
					Literal.width * 1024 / jinganw,
					Literal.width * 702 / jinganw,
					Literal.width * 1024 / jinganw,
					Literal.width * 801 / jinganw,
					Literal.width * 891 / jinganw,
					Literal.width * 801 / jinganw },
			{/* B超121 */Literal.width * 891 / jinganw,
					Literal.width * 805 / jinganw,
					Literal.width * 1024 / jinganw,
					Literal.width * 805 / jinganw,
					Literal.width * 1024 / jinganw,
					Literal.width * 925 / jinganw,
					Literal.width * 891 / jinganw,
					Literal.width * 925 / jinganw },
			{/* 女内科128 */Literal.width * 632 / jinganw,
					Literal.width * 598 / jinganw,
					Literal.width * 788 / jinganw,
					Literal.width * 598 / jinganw,
					Literal.width * 788 / jinganw,
					Literal.width * 678 / jinganw,
					Literal.width * 632 / jinganw,
					Literal.width * 678 / jinganw },
			{/* 女外科127 */Literal.width * 632 / jinganw,
					Literal.width * 682 / jinganw,
					Literal.width * 788 / jinganw,
					Literal.width * 682 / jinganw,
					Literal.width * 788 / jinganw,
					Literal.width * 761 / jinganw,
					Literal.width * 632 / jinganw,
					Literal.width * 761 / jinganw },
			{/* 妇科126 */Literal.width * 632 / jinganw,
					Literal.width * 765 / jinganw,
					Literal.width * 788 / jinganw,
					Literal.width * 765 / jinganw,
					Literal.width * 788 / jinganw,
					Literal.width * 840 / jinganw,
					Literal.width * 632 / jinganw,
					Literal.width * 840 / jinganw },
			{/* 妇科125 */Literal.width * 632 / jinganw,
					Literal.width * 844 / jinganw,
					Literal.width * 788 / jinganw,
					Literal.width * 844 / jinganw,
					Literal.width * 788 / jinganw,
					Literal.width * 924 / jinganw,
					Literal.width * 632 / jinganw,
					Literal.width * 924 / jinganw },
			{/* 妇科000 */Literal.width * 1523 / jinganw,
					Literal.width * 256 / jinganw,
					Literal.width * 1731 / jinganw,
					Literal.width * 256 / jinganw,
					Literal.width * 1731 / jinganw,
					Literal.width * 356 / jinganw,
					Literal.width * 1523 / jinganw,
					Literal.width * 356 / jinganw } };

}
